name: locker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  # flutter_svg: ^1.0.0
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter_secure_storage: ^6.0.0
  dio: ^4.0.6
  equatable: ^2.0.5
  meta: ^1.3.0
  http: ^0.13.4
  dependencies:
  hexcolor: ^3.0.1
  timelines: ^0.1.0
  #onesignal_flutter: ^3.4.2
  font_awesome_flutter: ^9.1.0
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  firebase_auth: ^4.1.3
  google_sign_in: '^4.5.1'
  #flutter_facebook_auth: '^3.5.0'
  onboarding: ^3.1.0
  flutter_local_notifications: ^12.0.3+1
  flutter_facebook_auth: ^5.0.6
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.15
  flutter_svg: ^1.1.6
  sweetalertv2: ^0.0.2
  provider: ^6.0.4
  social_login_buttons: ^1.0.7
  flutter_launcher_icons: ^0.11.0
  toast: ^0.3.0
  
dependency_overrides:
  font_awesome_flutter:
    path: fonts/font_awesome_flutter

dev_dependencies: 
  flutter_test:
    sdk: flutter
  # change_app_package_name: ^1.0.0
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logov2.ico"
  adaptive_icon_background: "assets/logov2.ico"

flutter_native_splash:
  color: "#fefeff"
  color_dark: "#fefeff"
  image: "assets/logo_big.png"
  image:_dark: "assets/logo_big.png"

  android_12:
    icon_background_color: "#fefeff"
    icon_background_color_dark: "#fefeff"
    image: "assets/logo_big.png"
    image:_dark: "assets/logo_big.png"
  
  web: false  


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: Exo
      fonts:
        - asset: fonts/exo2/Exo2-Regular.otf
        - asset: fonts/exo2/Exo2-Bold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
